/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AgendaController;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author perolanegra
 */
public class Agenda extends javax.swing.JFrame {
    private final AgendaController controller;
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        this.controller = new AgendaController(this);
        controller.listarValoresAgendamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        DebitoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clientField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        workField = new javax.swing.JTextField();
        dataField = new javax.swing.JTextField();
        horaField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAgendamento = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnAgend = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("URW Bookman L", 2, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("(Para a exclusão é necessario somento o ID)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 570, 220, 30));

        jLabel2.setFont(new java.awt.Font("URW Bookman L", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Situação");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 270, 180, 80));

        jLabel8.setFont(new java.awt.Font("URW Bookman L", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 140, 80));

        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 440, 80, 30));

        DebitoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DebitoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 350, 80, 30));

        jLabel4.setFont(new java.awt.Font("URW Bookman L", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 140, 80));

        jLabel5.setFont(new java.awt.Font("URW Bookman L", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Horario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 140, 80));

        clientField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clientField, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 230, 30));

        jLabel6.setFont(new java.awt.Font("URW Bookman L", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serviço");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 140, 80));

        jLabel9.setFont(new java.awt.Font("URW Bookman L", 2, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 370, 140, 80));

        btnDelete.setText("Excluir");
        btnDelete.setToolTipText("");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 530, 160, 40));

        workField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workFieldActionPerformed(evt);
            }
        });
        getContentPane().add(workField, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 230, 30));

        dataField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dataField, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 230, 30));

        horaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(horaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 230, 30));

        TableAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Horario", "Serviço", "Funcionario", "Cliente", "Debitos"
            }
        ));
        jScrollPane2.setViewportView(TableAgendamento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 810, 160));

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 110, 20));

        btnUpdate.setText("Atualizar");
        btnUpdate.setToolTipText("");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, 160, 40));

        btnSearch.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 160, 40));

        btnAgend.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        btnAgend.setText("Agendar");
        btnAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgend, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/box.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 1090, 840));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -1250, 3650, 4810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientFieldActionPerformed

    private void dataFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFieldActionPerformed

    private void horaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaFieldActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.alterarAgendamento();
        controller.LimparCamposAgendamento();
        controller.listarValoresAgendamento();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        controller.pesquisarAgendamento();
        controller.LimparCamposAgendamento();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendActionPerformed
        // TODO add your handling code here:
        controller.cadastrarAgendamento();
        controller.listarValoresAgendamento();
        controller.LimparCamposAgendamento();
    }//GEN-LAST:event_btnAgendActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.controller.voltarParaMenu();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void workFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workFieldActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.ExcluirAgendamento();
        controller.listarValoresAgendamento();
        controller.LimparCamposAgendamento();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    private void DebitoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DebitoFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DebitoField;
    private javax.swing.JTextField IdField;
    private javax.swing.JTable TableAgendamento;
    private javax.swing.JButton btnAgend;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField clientField;
    private javax.swing.JTextField dataField;
    private javax.swing.JTextField horaField;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField workField;
    // End of variables declaration//GEN-END:variables

    public JTable getTableAgendamento() {
        return TableAgendamento;
    }

    public JTextField getClientField() {
        return clientField;
    }

    public JTextField getDataField() {
        return dataField;
    }

    public JTextField getHoraField() {
        return horaField;
    }

    public JTextField getWorkField() {
        return workField;
    }

    public JTextField getIdField() {
        return IdField;
    }

    public JTextField getDebitoField() {
        return DebitoField;
    }


}



