/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CadastroController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.DAO.FuncionarioDAO;
import model.DAO.FuncionarioDTO;

/**
 *
 * @author perolanegra
 */
public class Cadastro extends javax.swing.JFrame {

    private final CadastroController controller;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        this.controller = new CadastroController(this);
        controller.listarValores();
        controller.listarValoresCliente();
        controller.listarValoresServico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jNameUserField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jField5 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        clientIDField = new javax.swing.JTextField();
        jButtonRegisterUsers3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clientNomeField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        clientEmailField = new javax.swing.JTextField();
        clientTelField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jNameWork = new javax.swing.JTextField();
        jValorWork = new javax.swing.JTextField();
        jDescribeWork = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Btnexcluir = new javax.swing.JButton();
        Btncadastro = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableWork = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        Btnpesquisar = new javax.swing.JButton();
        Btnatualizar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jIDWork = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jNameUserField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        clientBtnRegister = new javax.swing.JButton();
        clientBtnDelete = new javax.swing.JButton();
        clientBtnSearch = new javax.swing.JButton();
        clientBtnUpdate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Funcionarios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 260, 80));

        jNameUserField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameUserField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jNameUserField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 200, -1));

        jLabel5.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 140, 80));

        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, 230, -1));

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 240, 150, 20));

        jLabel12.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cargo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 140, 80));

        jLabel6.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 90, 140, 80));

        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 150, 100, 30));

        jLabel7.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 140, 80));

        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 150, 20));

        jField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 230, -1));

        btnSearch.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 160, 20));

        jLabel13.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 140, 80));

        jButton10.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jButton10.setText("Voltar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 100, 20));

        clientIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clientIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 30));

        jButtonRegisterUsers3.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jButtonRegisterUsers3.setText("Cadastrar");
        jButtonRegisterUsers3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterUsers3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegisterUsers3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 150, 20));

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cargo"
            }
        ));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 650, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/box.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 670, 310));

        jLabel8.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clientes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 260, 80));

        jLabel9.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, 50));

        clientNomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clientNomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, -1));

        jLabel10.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 80));

        clientEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientEmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clientEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 170, -1));

        clientTelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientTelFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clientTelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, 30));

        jLabel15.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Valor");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 140, 80));

        jNameWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameWorkActionPerformed(evt);
            }
        });
        getContentPane().add(jNameWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 190, 20));

        jValorWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorWorkActionPerformed(evt);
            }
        });
        getContentPane().add(jValorWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, 150, 30));

        jDescribeWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescribeWorkActionPerformed(evt);
            }
        });
        getContentPane().add(jDescribeWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 576, 230, 30));

        jLabel16.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Obs");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 140, 80));

        jLabel21.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nome ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 140, 80));

        Btnexcluir.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        Btnexcluir.setText("Excluir");
        Btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 150, 20));

        Btncadastro.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        Btncadastro.setText("Cadastrar");
        Btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncadastroActionPerformed(evt);
            }
        });
        getContentPane().add(Btncadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, 150, 20));

        jTableWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Valor", "Obs"
            }
        ));
        jTableWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableWorkMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableWork);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, 550, 90));

        jLabel19.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Serviço");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 470, 260, 50));

        Btnpesquisar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        Btnpesquisar.setText("Pesquisar");
        Btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Btnpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 610, 160, 20));

        Btnatualizar.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        Btnatualizar.setText("Atualizar");
        Btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnatualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Btnatualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 610, 150, 20));

        jLabel17.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ID");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 460, 140, 80));

        jIDWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDWorkActionPerformed(evt);
            }
        });
        getContentPane().add(jIDWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 520, 100, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/box.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 670, 310));

        jLabel20.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Senha");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 140, 80));

        jNameUserField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameUserField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jNameUserField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 200, 20));

        jLabel11.setFont(new java.awt.Font("URW Bookman L", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefone");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, 80));

        clientBtnRegister.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        clientBtnRegister.setText("Cadastrar");
        clientBtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBtnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(clientBtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, 20));

        clientBtnDelete.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        clientBtnDelete.setText("Excluir");
        clientBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(clientBtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 150, 20));

        clientBtnSearch.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        clientBtnSearch.setText("Pesquisar");
        clientBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBtnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(clientBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 160, 20));

        clientBtnUpdate.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        clientBtnUpdate.setText("Atualizar");
        clientBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(clientBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 160, 20));

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone"
            }
        ));
        jScrollPane3.setViewportView(clientTable);
        clientTable.getAccessibleContext().setAccessibleParent(jScrollPane3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 640, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/box.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 670, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/fundo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1560, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameUserField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameUserField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jNameUserField2ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        controller.AlterarFuncionario();
        controller.listarValores();
        controller.LimparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRegisterUsers3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterUsers3ActionPerformed
        // TODO add your handling code here:
        controller.cadastrarUsuario();
        controller.LimparCampos();
        controller.listarValores();
    }//GEN-LAST:event_jButtonRegisterUsers3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        controller.ExcluirFuncionario();
        controller.LimparCampos();
        controller.listarValores();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clientNomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNomeFieldActionPerformed

    private void clientEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientEmailFieldActionPerformed

    private void clientTelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientTelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTelFieldActionPerformed

    private void clientBtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBtnRegisterActionPerformed
        // TODO add your handling code here:
        controller.cadastrarCliente();
        controller.listarValoresCliente();
        controller.LimparCamposCliente();
    }//GEN-LAST:event_clientBtnRegisterActionPerformed

    private void clientBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBtnDeleteActionPerformed
        // TODO add your handling code here:
        controller.ExcluirCliente();
        controller.listarValoresCliente();
        controller.LimparCamposCliente();
    }//GEN-LAST:event_clientBtnDeleteActionPerformed

    private void clientBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBtnSearchActionPerformed
        // TODO add your handling code here:
        controller.pesquisarClientes();
        controller.LimparCamposCliente();
    }//GEN-LAST:event_clientBtnSearchActionPerformed

    private void clientBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBtnUpdateActionPerformed
        // TODO add your handling code here:
        controller.AlterarCliente();
        controller.listarValoresCliente();
        controller.LimparCamposCliente();
    }//GEN-LAST:event_clientBtnUpdateActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.controller.voltarParaMenu();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jField5ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        controller.pesquisarValores();
        controller.LimparCampos();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void clientIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientIDFieldActionPerformed

    private void jNameWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameWorkActionPerformed

    private void jValorWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorWorkActionPerformed

    private void jDescribeWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescribeWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescribeWorkActionPerformed

    private void BtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnexcluirActionPerformed
        // TODO add your handling code here:
        controller.ExcluirServico();
        controller.LimparCamposServico();
        controller.listarValoresServico();
    }//GEN-LAST:event_BtnexcluirActionPerformed

    private void BtncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncadastroActionPerformed
        // TODO add your handling code here:
        controller.cadastrarServico();
        controller.LimparCamposServico();
        controller.listarValoresServico();
    }//GEN-LAST:event_BtncadastroActionPerformed

    private void jTableWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableWorkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableWorkMouseClicked

    private void BtnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpesquisarActionPerformed
        // TODO add your handling code here:
        controller.pesquisarServico();
        controller.LimparCamposServico();
    }//GEN-LAST:event_BtnpesquisarActionPerformed

    private void BtnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnatualizarActionPerformed
        // TODO add your handling code here:
        controller.AlterarServico();
        controller.listarValoresServico();
        controller.LimparCamposServico();
    }//GEN-LAST:event_BtnatualizarActionPerformed

    private void jIDWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDWorkActionPerformed

    private void jNameUserField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameUserField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameUserField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnatualizar;
    private javax.swing.JButton Btncadastro;
    private javax.swing.JButton Btnexcluir;
    private javax.swing.JButton Btnpesquisar;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton clientBtnDelete;
    private javax.swing.JButton clientBtnRegister;
    private javax.swing.JButton clientBtnSearch;
    private javax.swing.JButton clientBtnUpdate;
    private javax.swing.JTextField clientEmailField;
    private javax.swing.JTextField clientIDField;
    private javax.swing.JTextField clientNomeField;
    private javax.swing.JTable clientTable;
    private javax.swing.JTextField clientTelField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonRegisterUsers3;
    private javax.swing.JTextField jDescribeWork;
    private javax.swing.JTextField jField5;
    private javax.swing.JTextField jIDWork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNameUserField2;
    private javax.swing.JTextField jNameUserField4;
    private javax.swing.JTextField jNameWork;
    private javax.swing.JTextField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTable jTableWork;
    private javax.swing.JTextField jValorWork;
    // End of variables declaration//GEN-END:variables

    

    public JTable getjTableUsuario() {
        return jTableUsuario;
    }

    public JTextField getTxtCodigo() {
        return TxtCodigo;
    }

    public JTextField getjField5() {
        return jField5;
    }

    public JTextField getjNameUserField2() {
        return jNameUserField2;
    }

    public JTextField getjPasswordField3() {
        return jPasswordField3;
    }

    public JTextField getClientEmailField() {
        return clientEmailField;
    }

    public JTextField getClientNomeField() {
        return clientNomeField;
    }

    public JTable getClientTable() {
        return clientTable;
    }

    public JTextField getClientTelField() {
        return clientTelField;
    }

    public JTextField getClientIDField() {
        return clientIDField;
    }

    public JTextField getjDescribeWork() {
        return jDescribeWork;
    }

    public JTextField getjIDWork() {
        return jIDWork;
    }

    public JTextField getjNameWork() {
        return jNameWork;
    }

    public JTextField getjValorWork() {
        return jValorWork;
    }

    public JTable getjTableWork() {
        return jTableWork;
    }



}
